### ISSUE TITLE
bulding analysis: hydrogen bonds as a case study

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#25]
- Show how to use MDAnalysis to build a hydrogen bond analysis from scratch. 
- Apply to the CG dataset #24.
- possibly compare to the built-in hbond analysis function?

Use the H-bond example for dask #20 (parallelize over trajectories?) and PMDA #21 (parallelize over a single trajectory).

blocked on: #24

**Comment by micaela-matta** [comment]
the analysis of hydrogen bonds is not applicable to the CG dataset.
I am coming up with another (big) all-atom system containing amphiphilic polymer chains in water where we can use hydrogen bonds and all polymer descriptors. 
For the fiber formation, I will calculate the radial density distribution, RDFs and other quantities.

**Comment by orbeckst** [comment]
Your notebook https://github.com/MDAnalysis/WorkshopHackathon2018/blob/master/04_Tutorial2/tutorial_PEG.ipynb says that the kernel dies. Is this a memory problem? Do you keep big arrays around?

**Comment by micaela-matta** [comment]
we found the problem and it's in capped_distance.. for some reason it dies for one particular frame which we removed from the trajectory. you can go ahead and use the code in the notebook I'm about to upload.
also please somebody use this [trajectory](https://figshare.com/s/f528467b80434293d4f7), because I spent 2 days on it :)
